const defenseStats = {
  defense: [
    { key: "tackles", label: "Tackles" },
    { key: "unassisted_tackles", label: "Solo Tackles" },
    { key: "tackles_for_loss", label: "Tackles for Loss" },
    { key: "qb_hits", label: "QB Hits" },
    { key: "sacks", label: "Sacks" },
    { key: "passes_defended", label: "Passes Defended" },
    { key: "forced_fumbles", label: "Forced Fumbles" },
    { key: "interceptions_for_tds", label: "Pick Six" },
    { key: "expected_return_td", label: "Expected TD Return" },
    { key: "kick_return_td", label: "Kick Return TD" },
    { key: "blocked_kicks", label: "Blocked Kicks" },
  ],
  interception: [
    { key: "total_interceptions", label: "Total Interceptions" },
    { key: "yards", label: "Yards" },
    { key: "intercepted_touch_downs", label: "Intercepted Touchdowns" },
  ],
  fumble: [
    { key: "fumble_lost", label: "Fumble Lost" },
    { key: "fumble_recovery", label: "Fumble Recovery" },
    { key: "fumble_recovery_td", label: "Fumble Recovery for TD" },
    { key: "total_fumbles", label: "Total Fumbles" },
  ],
};

export const positionStatsGroup = {
  // OFFENSE
  QB: {
    passing: [
      { key: "passing_completion", label: "Passing Completions" },
      { key: "passing_attempted", label: "Passing Attempts" },
      { key: "passing_average", label: "Passing Average" },
      { key: "passer_rating", label: "Passer Rating" },
      { key: "passing_yards", label: "Passing yards" },
      { key: "passing_touch_downs", label: "Passing Toushdowns" },
      { key: "passing_interceptions", label: "Interceptions" },
      { key: "sacks_total", label: "Sacks" },
      { key: "sacks_yards", label: "Sack Yards" },
      { key: "two_point_conversions", label: "Two-point Conversions" },
    ],
    rushing: [
      { key: "total_rushes", label: "Total Rushes" },
      { key: "rushing_yards", label: "Rushing Yards" },
      { key: "rushing_average", label: "Rushing Average" },
      { key: "rushing_touchdowns", label: "Rushing Touchdowns" },
      { key: "longest_rush", label: "Longest Rush" },
      { key: "exp_return_touchdowns", label: "Expected Touchdown Return" },
      { key: "kick_return_touchdowns", label: "Kick Return Touchdowns" },
      { key: "two_point_rushes", label: "Two Point Rushes" },
    ],
    fumble: [
      { key: "fumble_lost", label: "Fumble Lost" },
      { key: "fumble_recovery", label: "Fumble Recovery" },
      { key: "fumble_recovery_td", label: "Fumble Recovery for TD" },
      { key: "total_fumbles", label: "Total Fumbles" },
    ],
  },
  RB: {
    rushing: [
      { key: "total_rushes", label: "Total Rushes" },
      { key: "rushing_yards", label: "Rushing Yards" },
      { key: "rushing_average", label: "Rushing Average" },
      { key: "rushing_touchdowns", label: "Rushing Touchdowns" },
      { key: "longest_rush", label: "Longest Rush" },
      { key: "exp_return_touchdowns", label: "Expected Touchdown Return" },
      { key: "kick_return_touchdowns", label: "Kick Return Touchdowns" },
      { key: "two_point_rushes", label: "Two Point Rushes" },
    ],
    receiving: [
      { key: "receiving_targets", label: " Targets" },
      { key: "total_receptions", label: "Receptions" },
      { key: "receiving_yards", label: "Yards" },
      { key: "receiving_average", label: "Average" },
      { key: "receiving_touchdowns", label: "Receiving Touchdowns" },
      { key: "longest_reception", label: "Longest Reception" },
      { key: "two_point_receptions", label: "Two Point Receptions" },
    ],
    fumble: [
      { key: "fumble_lost", label: "Fumble Lost" },
      { key: "fumble_recovery", label: "Fumble Recovery" },
      { key: "fumble_recovery_td", label: "Fumble Recovery for TD" },
      { key: "total_fumbles", label: "Total Fumbles" },
    ],
  },
  WR: {
    receiving: [
      { key: "receiving_targets", label: " Targets" },
      { key: "total_receptions", label: "Receptions" },
      { key: "receiving_yards", label: "Yards" },
      { key: "receiving_average", label: "Average" },
      { key: "receiving_touchdowns", label: "Receiving Touchdowns" },
      { key: "longest_reception", label: "Longest Reception" },
      { key: "two_point_receptions", label: "Two Point Receptions" },
    ],
    rushing: [
      { key: "total_rushes", label: "Total Rushes" },
      { key: "rushing_yards", label: "Rushing Yards" },
      { key: "rushing_average", label: "Rushing Average" },
      { key: "rushing_touchdowns", label: "Rushing Touchdowns" },
      { key: "longest_rush", label: "Longest Rush" },
      { key: "exp_return_touchdowns", label: "Expected Touchdown Return" },
      { key: "kick_return_touchdowns", label: "Kick Return Touchdowns" },
      { key: "two_point_rushes", label: "Two Point Rushes" },
    ],
  },
  TE: {
    receiving: [
      { key: "receiving_targets", label: " Targets" },
      { key: "total_receptions", label: "Receptions" },
      { key: "receiving_yards", label: "Yards" },
      { key: "receiving_average", label: "Average" },
      { key: "receiving_touchdowns", label: "Receiving Touchdowns" },
      { key: "longest_reception", label: "Longest Reception" },
      { key: "two_point_receptions", label: "Two Point Receptions" },
    ],
    rushing: [
      { key: "total_rushes", label: "Total Rushes" },
      { key: "rushing_yards", label: "Rushing Yards" },
      { key: "rushing_average", label: "Rushing Average" },
      { key: "rushing_touchdowns", label: "Rushing Touchdowns" },
      { key: "longest_rush", label: "Longest Rush" },
      { key: "exp_return_touchdowns", label: "Expected Touchdown Return" },
      { key: "kick_return_touchdowns", label: "Kick Return Touchdowns" },
      { key: "two_point_rushes", label: "Two Point Rushes" },
    ],
    fumble: [
      { key: "fumble_lost", label: "Fumble Lost" },
      { key: "fumble_recovery", label: "Fumble Recovery" },
      { key: "fumble_recovery_td", label: "Fumble Recovery for TD" },
      { key: "total_fumbles", label: "Total Fumbles" },
    ],
  },

  // DEFENSE
  CB: { ...defenseStats },
  DE: { ...defenseStats },
  DT: { ...defenseStats },
  LB: { ...defenseStats },
  S: { ...defenseStats },
  default: {},
};
